name: scp8
description: Dart CLI to easily start a Flutter project following SCP Architecture.
version: 1.3.3

environment:
  sdk: '>=2.15.1 <3.0.0'

executables:
  scp: scp8

dependencies: 
  args: ^2.3.0
  interact: ^2.1.1
  linter: ^1.17.1

dev_dependencies:
  lints: ^1.0.0
